{
  "civilizaciones":[
    {
      "id": 1,
      "name": "Portugugal",
      "nacionality": "Portugueses",
      "flag": "",
      "IA": "Enrique el Navegante",
      "Effect": "recive un carreton de Centro Urbano con cada Avance de Edad",
      "Royal_Guard_1": "Ballestero",
      "Royal_Guard_2": "Mosquetero",
      "Royal_Guard_3": "Dragon",
      "Unit_Unique_1": "Cassador",
      "Unit_Unique_2": "Cañon de Salvas",
      "Unit_Unique_3": " ",
      "Unit_Unique_4": " ",
      "Bulding_Unique_1": " ",
      "Bulding_Unique_2": " ",
      "Bulding_Unique_3": " ",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Europa",
      "type_arquitecture_1": "Mediterranea",
      "type_arquitecture_2": " ",
      "metropolis": "Lisboa",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 2,
      "name": "España",
      "nacionality": "Españoles",
      "flag": "",
      "IA": "Isabel la Catolica",
      "Effect": "Los Envios llegan mas rapido",
      "Royal_Guard_1": "Piquero",
      "Royal_Guard_2": "Rodelero",
      "Royal_Guard_3": "Lancero",
      "Unit_Unique_1": "Rodelero",
      "Unit_Unique_2": "Lancero",
      "Unit_Unique_3": "Perro de Guerra",
      "Unit_Unique_4": "Misionero",
      "Bulding_Unique_1": " ",
      "Bulding_Unique_2": " ",
      "Bulding_Unique_3": " ",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Europa",
      "type_arquitecture_1": "Mediterranea",
      "type_arquitecture_2": " ",
      "metropolis": "Sevilla",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 3,
      "name": "Francia",
      "nacionality": "Franceses",
      "flag": "",
      "IA": "Napoleon Bonaparte",
      "Effect": "Los Coureurs des Bois reemplazan a los colonos, recolectan recursos mas rapidos y son mejores en combate, pero mas caros",
      "Royal_Guard_1": "Guerrillero",
      "Royal_Guard_2": "Curassier",
      "Royal_Guard_3": " ",
      "Unit_Unique_1": "Coureurs des Bois ",
      "Unit_Unique_2": "Curassier",
      "Unit_Unique_3": " ",
      "Unit_Unique_4": " ",
      "Bulding_Unique_1": " ",
      "Bulding_Unique_2": " ",
      "Bulding_Unique_3": " ",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Europa",
      "type_arquitecture_1": "Europa Occidental",
      "type_arquitecture_2": " ",
      "metropolis": "Paris",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 4,
      "name": "Holanda",
      "nacionality": "Holandeses",
      "flag": "",
      "IA": "Mauricio de Nassau-Orange",
      "Effect": "los Colonos custan monedas y no comida, se puede tener maximo 50, pero recolectan 50% mas rapido de las minas",
      "Royal_Guard_1": "Alabardero",
      "Royal_Guard_2": "Ruyter",
      "Royal_Guard_3": " ",
      "Unit_Unique_1": "Emisario",
      "Unit_Unique_2": "Ruyter",
      "Unit_Unique_3": "Filibote",
      "Unit_Unique_4": " ",
      "Bulding_Unique_1": "Banco",
      "Bulding_Unique_2": " ",
      "Bulding_Unique_3": " ",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Europa",
      "type_arquitecture_1": "Europa Occidental",
      "type_arquitecture_2": " ",
      "metropolis": "Amsterdam",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 5,
      "name": "Reino Unido",
      "nacionality": "Britanicos",
      "flag":"",
      "IA": "Isabel I de Inglaterra",
      "Effect": "las casas solariegas producen un aldeano al ser creadas",
      "Royal_Guard_1": "Mosquetero",
      "Royal_Guard_2": "Husar",
      "Royal_Guard_3": " ",
      "Unit_Unique_1": "Arquero de Tiro Largo",
      "Unit_Unique_2": "Ranger",
      "Unit_Unique_3": "Cohete",
      "Unit_Unique_4": "Barco de Guerra",
      "Bulding_Unique_1": " ",
      "Bulding_Unique_2": " ",
      "Bulding_Unique_3": " ",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Europa",
      "type_arquitecture": "Europa Occidental",
      "type_arquitecture": " ",
      "metropolis": "Londres",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 6,
      "name": "Alemania",
      "nacionality": "Alemanes",
      "flag":"",
      "IA": "Federico el Grande de Prusia",
      "Effect": "recives Ulanos gratis con cada Envio",
      "Royal_Guard_1": "Guerrillero",
      "Royal_Guard_2": "Ulano",
      "Royal_Guard_3": " ",
      "Unit_Unique_1": "Carreton Colono",
      "Unit_Unique_2": "Doppelsoldner",
      "Unit_Unique_3": "Ulano",
      "Unit_Unique_4": "Carreta de Guerra",
      "Bulding_Unique_1": " ",
      "Bulding_Unique_2": " ",
      "Bulding_Unique_3": " ",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Europa",
      "type_arquitecture_1": "Europa Oriental",
      "type_arquitecture_2": " ",
      "metropolis": "Berlin",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 7,
      "name": "Suecia",
      "nacionality":"Suecos",
      "flag":"",
      "IA": "Gustavo Adolfo",
      "Effect": "las cavañas recolectan recursos, envios de Mercenarios y Arcenal Avanzado Activados",
      "Royal_Guard_1": "Piqueros",
      "Royal_Guard_2": "Hakkpelitas",
      "Royal_Guard_3": " ",
      "Unit_Unique_1": "Carolinos",
      "Unit_Unique_2": "Hakkpelitas",
      "Unit_Unique_3": "Cañon de Cuero",
      "Unit_Unique_4": " ",
      "Bulding_Unique_1": "Cabañas",
      "Bulding_Unique_2": " ",
      "Bulding_Unique_3": " ",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Europa",
      "type_arquitecture_1": "Europa Oriental",
      "type_arquitecture_2": " ",
      "metropolis": "Estocolmo",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 8,
      "name": "Rusia",
      "nacionality": "Rusos",
      "flag":"",
      "IA": "Ivan el Terrible",
      "Effect": "los Colonos y la Infanteria se crean en grupos, los blocaos reemplazan a las Barracas y a los Destacamentos",
      "Royal_Guard_1": "Arqueros Montados",
      "Royal_Guard_2": "Granaderos",
      "Royal_Guard_3": " ",
      "Unit_Unique_1": "Strelets",
      "Unit_Unique_2": "Cosacos",
      "Unit_Unique_3": "Oprichnik",
      "Unit_Unique_4": " ",
      "Bulding_Unique_1": "Blocaos",
      "Bulding_Unique_2": " ",
      "Bulding_Unique_3": " ",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Europa",
      "type_arquitecture_1": "Europa Oriental",
      "type_arquitecture_2": " ",
      "metropolis": "San Petesburgo",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 9,
      "name": "Turquia",
      "nacionaliy": "Otomanos",
      "flag":"",
      "IA": "Soliman el Magnifico",
      "Effect": "los Centros Urbanos crean Colonos automaticamente, pueden crearse mas rapido por mejoras de la Mezquita",
      "Royal_Guard_1": "Husar",
      "Royal_Guard_2": "Granadero",
      "Royal_Guard_3": " ",
      "Unit_Unique_1": "Iman",
      "Unit_Unique_2": "Jenizaro",
      "Unit_Unique_3": "Fusilero Nizam",
      "Unit_Unique_4": "Obus",
      "Unit_Unique_5": "Gran Bombarda",
      "Unit_Unique_6": "Galera",
      "Bulding_Unique_1": "Mezquita",
      "Bulding_Unique_2": " ",
      "Bulding_Unique_3": " ",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Europa",
      "type_arquitecture_1": "Mediterranea",
      "type_arquitecture_2": " ",
      "metropolis": "Estambul",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 10,
      "name": "Azteca",
      "nacionality":"Aztecas",
      "flag": "",
      "IA": "Cuauhtemoc",
      "Effect": "los Monje Guerreros danzan en las plazas comunitarias y cuentan por 2 unidades",
      "Royal_Guard_1": "Caballero Jaguar",
      "Royal_Guard_2": "Caballero Craneo",
      "Royal_Guard_3": "",
      "Unit_Unique_1": "Explorador Aguila",
      "Unit_Unique_2": "Monje Guerrero",
      "Unit_Unique_3": "Corredor Coyote",
      "Unit_Unique_4": "Boleador Otontin",
      "Unit_Unique_5": "Lancero Puma",
      "Unit_Unique_6": "Caballero Flecha",
      "Unit_Unique_7": "Caballero Aguila",
      "Unit_Unique_8": "Caballero Jaguar",
      "Unit_Unique_9": "Caballero Flecha",
      "Unit_Unique_10": "Caballero Craneo",
      "Unit_Unique_11": "Canoa Tlaloc",
      "Bulding_Unique_1": "Barracon Noble",
      "Bulding_Unique_2": " ",
      "Bulding_Unique_3": " ",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "America",
      "type_arquitecture_1": "azteca",
      "type_arquitecture_2": " ",
      "metropolis": "Tenochtitlan",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 11,
      "name": "Inca",
      "nacionality": "Incas",
      "flag":"",
      "IA": "Huayna Capac",
      "Effect": "Recives un Chasqui con cada avance de edad",
      "Royal_Guard_1": "",
      "Royal_Guard_2": "",
      "Royal_Guard_3": "",
      "Unit_Unique_1": "Sacerdotiza",
      "Unit_Unique_2": "Chasqui",
      "Unit_Unique_3": "Lancero Emplumado",
      "Unit_Unique_4": "Corredor Chimu",
      "Unit_Unique_5": "Arquero de la Selva",
      "Unit_Unique_6": "Guerrero con Boleadoras",
      "Unit_Unique_7": "Huaraca",
      "Unit_Unique_8": "Guerrero con Maza",
      "Unit_Unique_9": "Bote Chincha",
      "Unit_Unique_10": "",
      "Unit_Unique_11": "",
      "Bulding_Unique_1": "Kancha",
      "Bulding_Unique_2": "Tambo",
      "Bulding_Unique_3": "Callanca",
      "Bulding_Unique_4": "Pucara",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "America",
      "type_arquitecture": "inca",
      "metropolis": "Cuzco",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 12,
      "name": "Haudenosaunense",
      "nacionality":"Haudenosaunenses",
      "flag":"",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "America precolonial",
      "type_arquitecture": "Haudenosaunense",
      "metropolis": "Caughnawaga",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 13,
      "name": "Lakota",
      "nacionality":"Lakotas",
      "flag":"",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "America precolonial",
      "type_arquitecture": "lakotas",
      "metropolis": "Gran Consejo",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 13,
      "name": "India",
      "nacionality": "Indios",
      "flag":"",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Asia",
      "type_arquitecture": "india",
      "metropolis": "Dehli",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 14,
      "name": "China",
      "nacionality": "Chinos",
      "flag":"",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Asia",
      "type_arquitecture": "china",
      "metropolis": "Pekin",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 15,
      "name": "Japon",
      "nacionality":"Japoneses",
      "flag":"",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Asia",
      "type_arquitecture": "japonesa",
      "metropolis": "Edo",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 16,
      "name": "Estados Unidos",
      "nacionality":"EstadoUnidenses",
      "flag":"flag",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Norte America",
      "type_arquitecture": "Europa Occidental",
      "metropolis": "Washington D.C",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 17,
      "name": "Mexico",
      "nacionality":"Mexicanos",
      "flag":"",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Norte America",
      "type_arquitecture": "mediterranea",
      "metropolis": "Ciudad de Mexico",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 18,
      "name": "Etiopia",
      "nacionality":"Etiopes",
      "flag":"",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Africa",
      "type_arquitecture": "Etiope",
      "metropolis": "Gondar",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 19,
      "name": "Hausa",
      "nacionality":"Hausa",
      "flag":"",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Africa",
      "type_arquitecture": "Hausa",
      "metropolis": "Kano",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 20,
      "name": "Argentina",
      "nacionality":"Argentinos",
      "flag":"",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "SudAmerica",
      "type_arquitecture": "mediterranea",
      "metropolis": "Buenos Aires",
      "revolucion": "si",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": "0",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 21,
      "name": "Baja California",
      "nacionality": "BajaCaliforneanos",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "SudAmerica",
      "type_arquitecture": "mediterranea",
      "metropolis": "La Paz",
      "revolucion": "si",
      "id_civ_origin_1": 17,
      "name_civ_origin_1": "Mexico",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 22,
      "name": "Argelia",
      "nacionality": "Berberiscos",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Africa",
      "type_arquitecture": "mediterranea",
      "metropolis": "Argel",
      "revolucion": "si",
      "id_civ_origin_1": 1,
      "name_civ_origin_1": "Portugal",
      "id_civ_origin_2": 9,
      "name_civ_origin_2": "Turquia",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 23,
      "name": "Brasil",
      "nacionality": "Brasileros",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "SudAmerica",
      "type_arquitecture": "mediterranea",
      "metropolis": "Rio de Janeiro",
      "revolucion": "si",
      "id_civ_origin_1": 1,
      "name_civ_origin_1": "Portugal",
      "id_civ_origin_2": 4,
      "name_civ_origin_2": "Holanda",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 24,
      "name": "California",
      "nacionality": "Californeanos",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "NorteAmerica",
      "type_arquitecture": "mediterranea",
      "metropolis": "Sonoma",
      "revolucion": "si",
      "id_civ_origin_1": 17,
      "name_civ_origin_1": "Mexico",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 25,
      "name": "Canada",
      "nacionality": "Canadiense",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "NorteAmerica",
      "type_arquitecture": "Europa Occidental",
      "metropolis": "Quebec",
      "revolucion": "si",
      "id_civ_origin_1": 5,
      "name_civ_origin_1": "Reino Unido",
      "id_civ_origin_2": 3,
      "name_civ_origin_2": "Francia",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 26,
      "name": "Centro America",
      "nacionality": "CentroAmericanos",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "CentroAmerica",
      "type_arquitecture": "mediterranea",
      "metropolis": "Ciudad de Guatemala",
      "revolucion": "si",
      "id_civ_origin_1": 17,
      "name_civ_origin_1": "Mexico",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 27,
      "name": "Chile",
      "nacionality": "Chilenos",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "SudAmerica",
      "type_arquitecture": "mediterranea",
      "metropolis": "Santiago",
      "revolucion": "si",
      "id_civ_origin_1": 2,
      "name_civ_origin_1": "España",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 28,
      "name": "Egipto",
      "nacionality": "Egipcios",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Africa",
      "type_arquitecture": "mediterranea",
      "metropolis": "El Cairo",
      "revolucion": "si",
      "id_civ_origin_1": 5,
      "name_civ_origin_1": "Reino Unido",
      "id_civ_origin_2": 9,
      "name_civ_origin_2": "Turquia",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 29,
      "name": "Finlandia",
      "nacionality": "Finlandeses",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Europa",
      "type_arquitecture": "Europa Oriental",
      "metropolis": "Helsinki",
      "revolucion": "si",
      "id_civ_origin_1": 7,
      "name_civ_origin_1": "Suecos",
      "id_civ_origin_2": 8,
      "name_civ_origin_2": "Rusos",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 30,
      "name": "Gran Colombia",
      "nacionality": "Colombianos",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "SudAmerica",
      "type_arquitecture": "mediterranea",
      "metropolis": "Bogota",
      "revolucion": "si",
      "id_civ_origin_1": 2,
      "name_civ_origin_1": "España",
      "id_civ_origin_2": 1,
      "name_civ_origin_2": "Portugal",
      "id_civ_origin_3": 6,
      "name_civ_origin_3": "Alemania",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 31,
      "name": "Haiti",
      "nacionality": "Haitianos",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Caribe",
      "type_arquitecture": "Europa Occidental",
      "metropolis": "Puerto Principe",
      "revolucion": "si",
      "id_civ_origin_1": 3,
      "name_civ_origin_1": "Francia",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 32,
      "name": "Hungria",
      "nacionality": "Hungaros",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Euroa",
      "type_arquitecture": "Europa Oriental",
      "metropolis": "Budapest",
      "revolucion": "si",
      "id_civ_origin_1": 6,
      "name_civ_origin_1": "Alemania",
      "id_civ_origin_2": 8,
      "name_civ_origin_2": "Rusia",
      "id_civ_origin_3": 9,
      "name_civ_origin_3": "Turquia",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 33,
      "name": "Indonesia",
      "nacionality": "Indonesios",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Sudeste Asiatico",
      "type_arquitecture_1": "Europa Occidental",
      "type_arquitecture_2": "mediterraneo",
      "metropolis": "Yogyakarta",
      "revolucion": "si",
      "id_civ_origin_1": 4,
      "name_civ_origin_1": "Holanda",
      "id_civ_origin_2": 1,
      "name_civ_origin_2": "Portugal",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 34,
      "name": "Maya",
      "nacionality": "Mayas",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "NorteAmerica",
      "type_arquitecture_1": "mediterranea",
      "type_arquitecture_2": " ",
      "metropolis": "Santa Cruz",
      "revolucion": "si",
      "id_civ_origin_1": 42,
      "name_civ_origin_1": "Yukatan",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 35,
      "name": "Mexico",
      "nacionality": "Mexicanos",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "NorteAmerica",
      "type_arquitecture_1": "mediterraneo",
      "type_arquitecture_2": " ",
      "metropolis": "Ciudad de Mexico",
      "revolucion": "si",
      "id_civ_origin_1": 2,
      "name_civ_origin_1": "España",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 36,
      "name": "Peru",
      "nacionality": "Peruanos",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Sudamerica",
      "type_arquitecture_1": "mediterraneo",
      "type_arquitecture_2": " ",
      "metropolis": "Lima",
      "revolucion": "si",
      "id_civ_origin_1": 2,
      "name_civ_origin_1": "España",
      "id_civ_origin_2": 1,
      "name_civ_origin_2": "Portugal",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 37,
      "name": "Rio Grande",
      "nacionality": "Rieños",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "NorteAmerica",
      "type_arquitecture_1": "mediterraneo",
      "type_arquitecture_2": " ",
      "metropolis": "Laredo",
      "revolucion": "si",
      "id_civ_origin_1": 17,
      "name_civ_origin_1": "Mexico",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 38,
      "name": "Rumania",
      "nacionality": "Rumanos",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Europa",
      "type_arquitecture_1": "mediterraneo",
      "type_arquitecture_2": "Europa Oriental",
      "metropolis": "Bucarest",
      "revolucion": "si",
      "id_civ_origin_1": 9,
      "name_civ_origin_1": "Otomanos",
      "id_civ_origin_2": 8,
      "name_civ_origin_2": "Rusos",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 39,
      "name": "Sudafrica",
      "nacionality": "Sudarica",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "Africa",
      "type_arquitecture_1": "Europa Occidental",
      "type_arquitecture_2": " ",
      "metropolis": "Pretoria",
      "revolucion": "si",
      "id_civ_origin_1": 5,
      "name_civ_origin_1": "Reino Unidos",
      "id_civ_origin_2": 4,
      "name_civ_origin_2": "Holanda",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 40,
      "name": "Texas",
      "nacionality": "Texas",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "NorteAmerica",
      "type_arquitecture_1": "mediterraneo",
      "type_arquitecture_2": " ",
      "metropolis": "Austin",
      "revolucion": "si",
      "id_civ_origin_1": 17,
      "name_civ_origin_1": "Mexico",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 41,
      "name": "Estados Unidos",
      "nacionality": "EstadoUnidenses",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "NorteAmerica",
      "type_arquitecture_1": "Europa Occidental",
      "type_arquitecture_2": "Europa Oriental",
      "metropolis": "Nueva York",
      "revolucion": "si",
      "id_civ_origin_1": 5,
      "name_civ_origin_1": "Reino Unido",
      "id_civ_origin_2": 4,
      "name_civ_origin_2": "Holanda",
      "id_civ_origin_3": 3,
      "name_civ_origin_3": "Francia",
      "id_civ_origin_4": 7,
      "name_civ_origin_4": "Suecia"
    },
    {
      "id": 42,
      "name": "Yucatan",
      "nacionality": "Yucatecos",
      "flag": "",
      "playable": "si",
      "type_culture": "escaramuza",
      "region": "NorteAmerica",
      "type_arquitecture_1": "mediterraneo",
      "type_arquitecture_2": " ",
      "metropolis": "Merida",
      "revolucion": "si",
      "id_civ_origin_1": 17,
      "name_civ_origin_1": "Mexico",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 43,
      "name": "Marruecos",
      "nacionality": "Marroqui",
      "flag": "",
      "playable": "no",
      "type_culture": "campaña",
      "region": "Africa",
      "type_arquitecture_1": "Mediterraneo",
      "type_arquitecture_2": "",
      "metropolis": "Marrakesh",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": " ",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 44,
      "name": "Somalia",
      "nacionality": "Somalies",
      "flag": "",
      "playable": "no",
      "type_culture": "campaña",
      "region": "Africa",
      "type_arquitecture_1": "Africa",
      "type_arquitecture_2": "",
      "metropolis": " ",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": " ",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 45,
      "name": "Piratas Berberiscos",
      "nacionality": "Piratas Berberiscos",
      "flag": "",
      "playable": "no",
      "type_culture": "campaña",
      "region": "Europa",
      "type_arquitecture_1": "Mediterraneo",
      "type_arquitecture_2": " ",
      "metropolis": "Cherchell",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": " ",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 46,
      "name": "Malta",
      "nacionality": "Caballeros de San Juan",
      "flag": "",
      "playable": "no",
      "type_culture": "campaña",
      "region": "Europa",
      "type_arquitecture_1": "Meditereanea",
      "type_arquitecture_2": "",
      "metropolis": "Malta",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": " ",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 47,
      "name": "Mercenarios de John Black",
      "nacionality": "Mercenarios de John Black",
      "flag": "",
      "playable": "no",
      "type_culture": "campaña",
      "region": "NorteAmerica",
      "type_arquitecture_1": "Europa Occidental",
      "type_arquitecture_2": "Europa Oriental",
      "metropolis": "Boston",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": " ",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },
    {
      "id": 48,
      "name": "El Circulo Oseus",
      "nacionality": "Circulo Oseus",
      "flag": "",
      "playable": "no",
      "type_culture": "campaña",
      "region": "Europa",
      "type_arquitecture_1": "Europa Oriental",
      "type_arquitecture_2": "Europa Occidental",
      "metropolis": " ",
      "revolucion": "no",
      "id_civ_origin_1": 0,
      "name_civ_origin_1": " ",
      "id_civ_origin_2": 0,
      "name_civ_origin_2": " ",
      "id_civ_origin_3": 0,
      "name_civ_origin_3": " ",
      "id_civ_origin_4": 0,
      "name_civ_origin_4": " "
    },




  ]
}